/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SaudeRouteImport } from './routes/saude'
import { Route as PergunteRouteImport } from './routes/pergunte'
import { Route as ObrasRouteImport } from './routes/obras'
import { Route as EducacaoRouteImport } from './routes/educacao'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LicitacoesIndexRouteImport } from './routes/licitacoes.index'
import { Route as EmpresasIndexRouteImport } from './routes/empresas.index'
import { Route as LicitacoesIdRouteImport } from './routes/licitacoes.$id'
import { Route as EmpresasIdRouteImport } from './routes/empresas.$id'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SaudeRoute = SaudeRouteImport.update({
  id: '/saude',
  path: '/saude',
  getParentRoute: () => rootRouteImport,
} as any)
const PergunteRoute = PergunteRouteImport.update({
  id: '/pergunte',
  path: '/pergunte',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrasRoute = ObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => rootRouteImport,
} as any)
const EducacaoRoute = EducacaoRouteImport.update({
  id: '/educacao',
  path: '/educacao',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LicitacoesIndexRoute = LicitacoesIndexRouteImport.update({
  id: '/licitacoes/',
  path: '/licitacoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasIndexRoute = EmpresasIndexRouteImport.update({
  id: '/empresas/',
  path: '/empresas/',
  getParentRoute: () => rootRouteImport,
} as any)
const LicitacoesIdRoute = LicitacoesIdRouteImport.update({
  id: '/licitacoes/$id',
  path: '/licitacoes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasIdRoute = EmpresasIdRouteImport.update({
  id: '/empresas/$id',
  path: '/empresas/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/educacao': typeof EducacaoRoute
  '/obras': typeof ObrasRoute
  '/pergunte': typeof PergunteRoute
  '/saude': typeof SaudeRoute
  '/sobre': typeof SobreRoute
  '/empresas/$id': typeof EmpresasIdRoute
  '/licitacoes/$id': typeof LicitacoesIdRoute
  '/empresas/': typeof EmpresasIndexRoute
  '/licitacoes/': typeof LicitacoesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/educacao': typeof EducacaoRoute
  '/obras': typeof ObrasRoute
  '/pergunte': typeof PergunteRoute
  '/saude': typeof SaudeRoute
  '/sobre': typeof SobreRoute
  '/empresas/$id': typeof EmpresasIdRoute
  '/licitacoes/$id': typeof LicitacoesIdRoute
  '/empresas': typeof EmpresasIndexRoute
  '/licitacoes': typeof LicitacoesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/educacao': typeof EducacaoRoute
  '/obras': typeof ObrasRoute
  '/pergunte': typeof PergunteRoute
  '/saude': typeof SaudeRoute
  '/sobre': typeof SobreRoute
  '/empresas/$id': typeof EmpresasIdRoute
  '/licitacoes/$id': typeof LicitacoesIdRoute
  '/empresas/': typeof EmpresasIndexRoute
  '/licitacoes/': typeof LicitacoesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/educacao'
    | '/obras'
    | '/pergunte'
    | '/saude'
    | '/sobre'
    | '/empresas/$id'
    | '/licitacoes/$id'
    | '/empresas/'
    | '/licitacoes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/educacao'
    | '/obras'
    | '/pergunte'
    | '/saude'
    | '/sobre'
    | '/empresas/$id'
    | '/licitacoes/$id'
    | '/empresas'
    | '/licitacoes'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/educacao'
    | '/obras'
    | '/pergunte'
    | '/saude'
    | '/sobre'
    | '/empresas/$id'
    | '/licitacoes/$id'
    | '/empresas/'
    | '/licitacoes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  EducacaoRoute: typeof EducacaoRoute
  ObrasRoute: typeof ObrasRoute
  PergunteRoute: typeof PergunteRoute
  SaudeRoute: typeof SaudeRoute
  SobreRoute: typeof SobreRoute
  EmpresasIdRoute: typeof EmpresasIdRoute
  LicitacoesIdRoute: typeof LicitacoesIdRoute
  EmpresasIndexRoute: typeof EmpresasIndexRoute
  LicitacoesIndexRoute: typeof LicitacoesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saude': {
      id: '/saude'
      path: '/saude'
      fullPath: '/saude'
      preLoaderRoute: typeof SaudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pergunte': {
      id: '/pergunte'
      path: '/pergunte'
      fullPath: '/pergunte'
      preLoaderRoute: typeof PergunteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obras': {
      id: '/obras'
      path: '/obras'
      fullPath: '/obras'
      preLoaderRoute: typeof ObrasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/educacao': {
      id: '/educacao'
      path: '/educacao'
      fullPath: '/educacao'
      preLoaderRoute: typeof EducacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licitacoes/': {
      id: '/licitacoes/'
      path: '/licitacoes'
      fullPath: '/licitacoes/'
      preLoaderRoute: typeof LicitacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas/': {
      id: '/empresas/'
      path: '/empresas'
      fullPath: '/empresas/'
      preLoaderRoute: typeof EmpresasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licitacoes/$id': {
      id: '/licitacoes/$id'
      path: '/licitacoes/$id'
      fullPath: '/licitacoes/$id'
      preLoaderRoute: typeof LicitacoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas/$id': {
      id: '/empresas/$id'
      path: '/empresas/$id'
      fullPath: '/empresas/$id'
      preLoaderRoute: typeof EmpresasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  EducacaoRoute: EducacaoRoute,
  ObrasRoute: ObrasRoute,
  PergunteRoute: PergunteRoute,
  SaudeRoute: SaudeRoute,
  SobreRoute: SobreRoute,
  EmpresasIdRoute: EmpresasIdRoute,
  LicitacoesIdRoute: LicitacoesIdRoute,
  EmpresasIndexRoute: EmpresasIndexRoute,
  LicitacoesIndexRoute: LicitacoesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
